# -*- coding: utf-8 -*-
"""rosalind_ba1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nqQS7VgFyKt2rA_jDUbBIeDMfrjftZNH
"""

def pattern_count(text, pattern):
    count = 0
    for i in range(0, len(text) - len(pattern) + 1):
        if text[i : len(pattern) + i] == pattern:
            count += 1
    return count
    
text = input()
pattern = input()
result = pattern_count(text,pattern)
print(result)