# -*- coding: utf-8 -*-
"""rosalindf_ba1c.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-H35Hu0mrvgn8oeZLutcRBPWwYLiLhls
"""

string = input()
ans = " "
for i in string:
  if(i=="A"):
    ans+="T"
  elif(i=="C"):
    ans+="G"
  elif(i=="G"):
    ans+="C"
  elif(i=="T"):
    ans+="A"
print(ans[::-1])