# -*- coding: utf-8 -*-
"""rosalind_ba1d.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gRLauXzuhz-ooGcuFius_fnvHeoCYIzn
"""

def pattern_matching(pattern, genome):
    for i in range(len(genome)-len(pattern)+1):
      if genome[i:i+len(pattern)] == pattern:
        print(i, end=" ")
    print()

pattern = input()
genome = input()
pattern_matching(pattern, genome)