# -*- coding: utf-8 -*-
"""ini3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w_t-veM-3IZ8lPfE8YXGMYDwOvZECpze
"""

s = input()
a = int(input())
b = int(input())
c = int(input())
d = int(input())
s1, s2 = slice(s, a, b, c, d)
print(s1, s2)