# -*- coding: utf-8 -*-
"""rosalindf_ba1g.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-H35Hu0mrvgn8oeZLutcRBPWwYLiLhls
"""

string1 = input();
string2 = input();
S1 = len(string1);
S1 = len(string2);
ans = 0;

for i in range(0, S1):
    if (string1[i] != string2[i]):
       ans+=1;
print(ans)