# -*- coding: utf-8 -*-
"""rosalind_ini2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xaUk7TDBQrER6yDLIFtv-7iZOpzuKrRy
"""

a=817 
b=805
print( a**2 + b**2 )