# -*- coding: utf-8 -*-
"""Set-B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mk6UyMEI0RHfj1d1MS7qbkNojizq_AMp
"""

def HammingDistance(s1, s2):
    d = 0
    for i in range(len(s1)):
        if s1[i] != s2[i]:
            d += 1
    return d

def ApproximatePattern(pattern, text, d):
    ans = " "
    tmp = 0
    for i in range(len(text)-len(pattern)+1):
        if HammingDistance(pattern, text[i:i+len(pattern)]) == d:
            tmp = 1
            for j in pattern:
                if(j=="A"):
                    ans+="T"
                elif(j=="C"):
                    ans+="G"
                elif(j=="G"):
                    ans+="C"
                elif(j=="T"):
                    ans+="A"
        else:
             count=0  
    if(tmp==1):
        print(ans)
    else:
        print("Hailey is unable to solve the riddle!")
    return ans
        

pattern = input()
text = input()
d = int(input())
ApproximatePattern(pattern, text, d)